// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: console_service.proto

package consolepb

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetAgentManifestRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Auth token. Required, fixed 36 chars (evt_ + 32 hex).
	Token         string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAgentManifestRequest) Reset() {
	*x = GetAgentManifestRequest{}
	mi := &file_console_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentManifestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentManifestRequest) ProtoMessage() {}

func (x *GetAgentManifestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_console_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentManifestRequest.ProtoReflect.Descriptor instead.
func (*GetAgentManifestRequest) Descriptor() ([]byte, []int) {
	return file_console_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetAgentManifestRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type GetAgentManifestResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// JSON consumed by rune-mcp's ParseManifestJSON:
	//
	//	{"agent_id","key_id","index_name","dim",
	//	 "rmp_enc_key": "<RMP (flat) EncKey envelope, verbatim JSON>",
	//	 "mm_enc_key":  "<MM (clustered) EncKey envelope, verbatim JSON>",
	//	 "agent_dek":   "<base64 32-byte metadata seal key>",
	//	 "centroid_set_version": "..."}
	//
	// The PUBLIC EncKey pair + agent_dek travel here; SecKey never does.
	ManifestJson  string `protobuf:"bytes,1,opt,name=manifest_json,json=manifestJson,proto3" json:"manifest_json,omitempty"`
	Error         string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"` // Non-empty on error
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAgentManifestResponse) Reset() {
	*x = GetAgentManifestResponse{}
	mi := &file_console_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentManifestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentManifestResponse) ProtoMessage() {}

func (x *GetAgentManifestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_console_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentManifestResponse.ProtoReflect.Descriptor instead.
func (*GetAgentManifestResponse) Descriptor() ([]byte, []int) {
	return file_console_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetAgentManifestResponse) GetManifestJson() string {
	if x != nil {
		return x.ManifestJson
	}
	return ""
}

func (x *GetAgentManifestResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetCACertRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCACertRequest) Reset() {
	*x = GetCACertRequest{}
	mi := &file_console_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCACertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCACertRequest) ProtoMessage() {}

func (x *GetCACertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_console_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCACertRequest.ProtoReflect.Descriptor instead.
func (*GetCACertRequest) Descriptor() ([]byte, []int) {
	return file_console_service_proto_rawDescGZIP(), []int{2}
}

type GetCACertResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CaPem         []byte                 `protobuf:"bytes,1,opt,name=ca_pem,json=caPem,proto3" json:"ca_pem,omitempty"` // PEM-encoded CA certificate chain (installer-issued ca.pem)
	Sha256        string                 `protobuf:"bytes,2,opt,name=sha256,proto3" json:"sha256,omitempty"`            // hex SHA-256 of ca_pem; the client verifies it against its pin
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`              // Non-empty on error
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCACertResponse) Reset() {
	*x = GetCACertResponse{}
	mi := &file_console_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCACertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCACertResponse) ProtoMessage() {}

func (x *GetCACertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_console_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCACertResponse.ProtoReflect.Descriptor instead.
func (*GetCACertResponse) Descriptor() ([]byte, []int) {
	return file_console_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetCACertResponse) GetCaPem() []byte {
	if x != nil {
		return x.CaPem
	}
	return nil
}

func (x *GetCACertResponse) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *GetCACertResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type InsertRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Auth token. Required, fixed 36 chars.
	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	// Caller-generated opaque UUID. Idempotency key: a re-insert of an existing
	// id is a server-side no-op, so an ack-loss retry MUST reuse the same id.
	Id string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	// FHE-encrypted flat-tier blob (SDK Keys.EncryptFlat output).
	RmpItem []byte `protobuf:"bytes,3,opt,name=rmp_item,json=rmpItem,proto3" json:"rmp_item,omitempty"`
	// FHE-encrypted clustered-tier blob (SDK Keys.EncryptClustered output).
	MmItem []byte `protobuf:"bytes,4,opt,name=mm_item,json=mmItem,proto3" json:"mm_item,omitempty"`
	// Hard single IVF cluster assignment (0..nlist-1), routed by rune-mcp against
	// the centroid set named by centroid_set_version.
	ClusterId uint32 `protobuf:"varint,5,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	// The centroid-set version the assignment was routed against. Required so the
	// server can reject a stale routing (ErrCentroidVersionMismatch).
	CentroidSetVersion string `protobuf:"bytes,6,opt,name=centroid_set_version,json=centroidSetVersion,proto3" json:"centroid_set_version,omitempty"`
	// Client-sealed metadata envelope ({"a","c"}), stored verbatim; may be empty.
	Metadata      string `protobuf:"bytes,7,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertRequest) Reset() {
	*x = InsertRequest{}
	mi := &file_console_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertRequest) ProtoMessage() {}

func (x *InsertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_console_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertRequest.ProtoReflect.Descriptor instead.
func (*InsertRequest) Descriptor() ([]byte, []int) {
	return file_console_service_proto_rawDescGZIP(), []int{4}
}

func (x *InsertRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *InsertRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *InsertRequest) GetRmpItem() []byte {
	if x != nil {
		return x.RmpItem
	}
	return nil
}

func (x *InsertRequest) GetMmItem() []byte {
	if x != nil {
		return x.MmItem
	}
	return nil
}

func (x *InsertRequest) GetClusterId() uint32 {
	if x != nil {
		return x.ClusterId
	}
	return 0
}

func (x *InsertRequest) GetCentroidSetVersion() string {
	if x != nil {
		return x.CentroidSetVersion
	}
	return ""
}

func (x *InsertRequest) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

type InsertResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`       // runespace-issued opaque id
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"` // Non-empty on error
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertResponse) Reset() {
	*x = InsertResponse{}
	mi := &file_console_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertResponse) ProtoMessage() {}

func (x *InsertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_console_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertResponse.ProtoReflect.Descriptor instead.
func (*InsertResponse) Descriptor() ([]byte, []int) {
	return file_console_service_proto_rawDescGZIP(), []int{5}
}

func (x *InsertResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *InsertResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetCentroidsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Auth token. Required, fixed 36 chars.
	Token         string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCentroidsRequest) Reset() {
	*x = GetCentroidsRequest{}
	mi := &file_console_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCentroidsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCentroidsRequest) ProtoMessage() {}

func (x *GetCentroidsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_console_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCentroidsRequest.ProtoReflect.Descriptor instead.
func (*GetCentroidsRequest) Descriptor() ([]byte, []int) {
	return file_console_service_proto_rawDescGZIP(), []int{6}
}

func (x *GetCentroidsRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// CentroidChunk is one framed piece of the centroid stream: exactly one Header
// arrives first, then any number of Batch messages (id-ordered centroid vectors).
type CentroidChunk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*CentroidChunk_Header
	//	*CentroidChunk_Batch
	Payload       isCentroidChunk_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CentroidChunk) Reset() {
	*x = CentroidChunk{}
	mi := &file_console_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CentroidChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CentroidChunk) ProtoMessage() {}

func (x *CentroidChunk) ProtoReflect() protoreflect.Message {
	mi := &file_console_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CentroidChunk.ProtoReflect.Descriptor instead.
func (*CentroidChunk) Descriptor() ([]byte, []int) {
	return file_console_service_proto_rawDescGZIP(), []int{7}
}

func (x *CentroidChunk) GetPayload() isCentroidChunk_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *CentroidChunk) GetHeader() *CentroidSetHeader {
	if x != nil {
		if x, ok := x.Payload.(*CentroidChunk_Header); ok {
			return x.Header
		}
	}
	return nil
}

func (x *CentroidChunk) GetBatch() *CentroidBatch {
	if x != nil {
		if x, ok := x.Payload.(*CentroidChunk_Batch); ok {
			return x.Batch
		}
	}
	return nil
}

type isCentroidChunk_Payload interface {
	isCentroidChunk_Payload()
}

type CentroidChunk_Header struct {
	Header *CentroidSetHeader `protobuf:"bytes,1,opt,name=header,proto3,oneof"`
}

type CentroidChunk_Batch struct {
	Batch *CentroidBatch `protobuf:"bytes,2,opt,name=batch,proto3,oneof"`
}

func (*CentroidChunk_Header) isCentroidChunk_Payload() {}

func (*CentroidChunk_Batch) isCentroidChunk_Payload() {}

type CentroidSetHeader struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"` // centroid-set version (matches GetAgentManifest)
	Dim           int32                  `protobuf:"varint,2,opt,name=dim,proto3" json:"dim,omitempty"`        // centroid vector dimension
	Preset        string                 `protobuf:"bytes,3,opt,name=preset,proto3" json:"preset,omitempty"`   // version-hash ingredient relayed to runed ("" if none)
	Nlist         int32                  `protobuf:"varint,4,opt,name=nlist,proto3" json:"nlist,omitempty"`    // total centroid count (stream length hint)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CentroidSetHeader) Reset() {
	*x = CentroidSetHeader{}
	mi := &file_console_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CentroidSetHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CentroidSetHeader) ProtoMessage() {}

func (x *CentroidSetHeader) ProtoReflect() protoreflect.Message {
	mi := &file_console_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CentroidSetHeader.ProtoReflect.Descriptor instead.
func (*CentroidSetHeader) Descriptor() ([]byte, []int) {
	return file_console_service_proto_rawDescGZIP(), []int{8}
}

func (x *CentroidSetHeader) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *CentroidSetHeader) GetDim() int32 {
	if x != nil {
		return x.Dim
	}
	return 0
}

func (x *CentroidSetHeader) GetPreset() string {
	if x != nil {
		return x.Preset
	}
	return ""
}

func (x *CentroidSetHeader) GetNlist() int32 {
	if x != nil {
		return x.Nlist
	}
	return 0
}

type CentroidBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Centroids     []*Centroid            `protobuf:"bytes,1,rep,name=centroids,proto3" json:"centroids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CentroidBatch) Reset() {
	*x = CentroidBatch{}
	mi := &file_console_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CentroidBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CentroidBatch) ProtoMessage() {}

func (x *CentroidBatch) ProtoReflect() protoreflect.Message {
	mi := &file_console_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CentroidBatch.ProtoReflect.Descriptor instead.
func (*CentroidBatch) Descriptor() ([]byte, []int) {
	return file_console_service_proto_rawDescGZIP(), []int{9}
}

func (x *CentroidBatch) GetCentroids() []*Centroid {
	if x != nil {
		return x.Centroids
	}
	return nil
}

type Centroid struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`           // centroid index (0..nlist-1) == the cluster id
	Vec           []float32              `protobuf:"fixed32,2,rep,packed,name=vec,proto3" json:"vec,omitempty"` // centroid vector
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Centroid) Reset() {
	*x = Centroid{}
	mi := &file_console_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Centroid) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Centroid) ProtoMessage() {}

func (x *Centroid) ProtoReflect() protoreflect.Message {
	mi := &file_console_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Centroid.ProtoReflect.Descriptor instead.
func (*Centroid) Descriptor() ([]byte, []int) {
	return file_console_service_proto_rawDescGZIP(), []int{10}
}

func (x *Centroid) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Centroid) GetVec() []float32 {
	if x != nil {
		return x.Vec
	}
	return nil
}

type SearchRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Auth token. Required, fixed 36 chars.
	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	// Plaintext query embedding. Length must equal the configured dim.
	Vector []float32 `protobuf:"fixed32,2,rep,packed,name=vector,proto3" json:"vector,omitempty"`
	// Number of top results. Per-role limits enforced at the business logic layer.
	TopK          int32 `protobuf:"varint,3,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_console_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_console_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_console_service_proto_rawDescGZIP(), []int{11}
}

func (x *SearchRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *SearchRequest) GetVector() []float32 {
	if x != nil {
		return x.Vector
	}
	return nil
}

func (x *SearchRequest) GetTopK() int32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

type SearchHit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Score         float64                `protobuf:"fixed64,2,opt,name=score,proto3" json:"score,omitempty"`
	Metadata      string                 `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"` // plaintext JSON (console opened the agent_dek envelope)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchHit) Reset() {
	*x = SearchHit{}
	mi := &file_console_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchHit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchHit) ProtoMessage() {}

func (x *SearchHit) ProtoReflect() protoreflect.Message {
	mi := &file_console_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchHit.ProtoReflect.Descriptor instead.
func (*SearchHit) Descriptor() ([]byte, []int) {
	return file_console_service_proto_rawDescGZIP(), []int{12}
}

func (x *SearchHit) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SearchHit) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *SearchHit) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

type SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hits          []*SearchHit           `protobuf:"bytes,1,rep,name=hits,proto3" json:"hits,omitempty"`   // ranked, score descending
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"` // Non-empty on error
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_console_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_console_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_console_service_proto_rawDescGZIP(), []int{13}
}

func (x *SearchResponse) GetHits() []*SearchHit {
	if x != nil {
		return x.Hits
	}
	return nil
}

func (x *SearchResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetPermissionsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Auth token. Required, fixed 36 chars.
	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	// Optional: restrict the returned tree to this group's subtree (id or name).
	RootGroup string `protobuf:"bytes,2,opt,name=root_group,json=rootGroup,proto3" json:"root_group,omitempty"`
	// When true, populate member_roles with the org-wide per-user (group, role)
	// listing. Organization admin only — a non-admin request is PermissionDenied.
	IncludeMemberRoles bool `protobuf:"varint,3,opt,name=include_member_roles,json=includeMemberRoles,proto3" json:"include_member_roles,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetPermissionsRequest) Reset() {
	*x = GetPermissionsRequest{}
	mi := &file_console_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPermissionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPermissionsRequest) ProtoMessage() {}

func (x *GetPermissionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_console_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPermissionsRequest.ProtoReflect.Descriptor instead.
func (*GetPermissionsRequest) Descriptor() ([]byte, []int) {
	return file_console_service_proto_rawDescGZIP(), []int{14}
}

func (x *GetPermissionsRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *GetPermissionsRequest) GetRootGroup() string {
	if x != nil {
		return x.RootGroup
	}
	return ""
}

func (x *GetPermissionsRequest) GetIncludeMemberRoles() bool {
	if x != nil {
		return x.IncludeMemberRoles
	}
	return false
}

// MembershipEntry is one direct (group, role) binding the caller holds.
type MembershipEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	GroupName     string                 `protobuf:"bytes,2,opt,name=group_name,json=groupName,proto3" json:"group_name,omitempty"`
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"` // read | write | edit
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MembershipEntry) Reset() {
	*x = MembershipEntry{}
	mi := &file_console_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MembershipEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MembershipEntry) ProtoMessage() {}

func (x *MembershipEntry) ProtoReflect() protoreflect.Message {
	mi := &file_console_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MembershipEntry.ProtoReflect.Descriptor instead.
func (*MembershipEntry) Descriptor() ([]byte, []int) {
	return file_console_service_proto_rawDescGZIP(), []int{15}
}

func (x *MembershipEntry) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *MembershipEntry) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *MembershipEntry) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

// TreeNode is one group the caller can reach by effective role, depth-annotated.
type TreeNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ParentId      string                 `protobuf:"bytes,3,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"` // empty for a root group
	Depth         int32                  `protobuf:"varint,4,opt,name=depth,proto3" json:"depth,omitempty"`                      // 0 = root of the group tree
	EffectiveRole string                 `protobuf:"bytes,5,opt,name=effective_role,json=effectiveRole,proto3" json:"effective_role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TreeNode) Reset() {
	*x = TreeNode{}
	mi := &file_console_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TreeNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TreeNode) ProtoMessage() {}

func (x *TreeNode) ProtoReflect() protoreflect.Message {
	mi := &file_console_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TreeNode.ProtoReflect.Descriptor instead.
func (*TreeNode) Descriptor() ([]byte, []int) {
	return file_console_service_proto_rawDescGZIP(), []int{16}
}

func (x *TreeNode) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *TreeNode) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TreeNode) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *TreeNode) GetDepth() int32 {
	if x != nil {
		return x.Depth
	}
	return 0
}

func (x *TreeNode) GetEffectiveRole() string {
	if x != nil {
		return x.EffectiveRole
	}
	return ""
}

// MemberRole is one org-wide (user, group, role) row (admin-only listing).
type MemberRole struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          string                 `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"` // email (the person key, plan §0)
	GroupId       string                 `protobuf:"bytes,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	GroupName     string                 `protobuf:"bytes,3,opt,name=group_name,json=groupName,proto3" json:"group_name,omitempty"`
	Role          string                 `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemberRole) Reset() {
	*x = MemberRole{}
	mi := &file_console_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemberRole) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberRole) ProtoMessage() {}

func (x *MemberRole) ProtoReflect() protoreflect.Message {
	mi := &file_console_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberRole.ProtoReflect.Descriptor instead.
func (*MemberRole) Descriptor() ([]byte, []int) {
	return file_console_service_proto_rawDescGZIP(), []int{17}
}

func (x *MemberRole) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *MemberRole) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *MemberRole) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *MemberRole) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type GetPermissionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Me            string                 `protobuf:"bytes,1,opt,name=me,proto3" json:"me,omitempty"`                                      // caller email
	Memberships   []*MembershipEntry     `protobuf:"bytes,2,rep,name=memberships,proto3" json:"memberships,omitempty"`                    // caller's direct bindings
	Tree          []*TreeNode            `protobuf:"bytes,3,rep,name=tree,proto3" json:"tree,omitempty"`                                  // reachable groups, depth-annotated
	MemberRoles   []*MemberRole          `protobuf:"bytes,4,rep,name=member_roles,json=memberRoles,proto3" json:"member_roles,omitempty"` // populated only for admin + include_member_roles
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`                                // Non-empty on error
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPermissionsResponse) Reset() {
	*x = GetPermissionsResponse{}
	mi := &file_console_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPermissionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPermissionsResponse) ProtoMessage() {}

func (x *GetPermissionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_console_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPermissionsResponse.ProtoReflect.Descriptor instead.
func (*GetPermissionsResponse) Descriptor() ([]byte, []int) {
	return file_console_service_proto_rawDescGZIP(), []int{18}
}

func (x *GetPermissionsResponse) GetMe() string {
	if x != nil {
		return x.Me
	}
	return ""
}

func (x *GetPermissionsResponse) GetMemberships() []*MembershipEntry {
	if x != nil {
		return x.Memberships
	}
	return nil
}

func (x *GetPermissionsResponse) GetTree() []*TreeNode {
	if x != nil {
		return x.Tree
	}
	return nil
}

func (x *GetPermissionsResponse) GetMemberRoles() []*MemberRole {
	if x != nil {
		return x.MemberRoles
	}
	return nil
}

func (x *GetPermissionsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type LookupWrapRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Invite code from the invite mail. Not a secret — a one-time claim ticket
	// pointing at the sealed token. Fixed 32 hex chars.
	Handle        string `protobuf:"bytes,1,opt,name=handle,proto3" json:"handle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LookupWrapRequest) Reset() {
	*x = LookupWrapRequest{}
	mi := &file_console_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupWrapRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupWrapRequest) ProtoMessage() {}

func (x *LookupWrapRequest) ProtoReflect() protoreflect.Message {
	mi := &file_console_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupWrapRequest.ProtoReflect.Descriptor instead.
func (*LookupWrapRequest) Descriptor() ([]byte, []int) {
	return file_console_service_proto_rawDescGZIP(), []int{19}
}

func (x *LookupWrapRequest) GetHandle() string {
	if x != nil {
		return x.Handle
	}
	return ""
}

type LookupWrapResponse struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Email     string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`                          // who the invite is for
	Role      string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`                            // token role the invite grants
	ExpiresAt string                 `protobuf:"bytes,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"` // RFC3339 UTC
	// Wrap-path binding (§8.3): which surface issued this wrap. The client
	// compares it against its baked expected constant to detect a wrap minted
	// by any other surface.
	CreationPath  string `protobuf:"bytes,4,opt,name=creation_path,json=creationPath,proto3" json:"creation_path,omitempty"`
	Error         string `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"` // Non-empty on error
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LookupWrapResponse) Reset() {
	*x = LookupWrapResponse{}
	mi := &file_console_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupWrapResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupWrapResponse) ProtoMessage() {}

func (x *LookupWrapResponse) ProtoReflect() protoreflect.Message {
	mi := &file_console_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupWrapResponse.ProtoReflect.Descriptor instead.
func (*LookupWrapResponse) Descriptor() ([]byte, []int) {
	return file_console_service_proto_rawDescGZIP(), []int{20}
}

func (x *LookupWrapResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LookupWrapResponse) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *LookupWrapResponse) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

func (x *LookupWrapResponse) GetCreationPath() string {
	if x != nil {
		return x.CreationPath
	}
	return ""
}

func (x *LookupWrapResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type UnwrapRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Invite code to consume — same one-time ticket LookupWrap pre-validates.
	Handle        string `protobuf:"bytes,1,opt,name=handle,proto3" json:"handle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnwrapRequest) Reset() {
	*x = UnwrapRequest{}
	mi := &file_console_service_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnwrapRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnwrapRequest) ProtoMessage() {}

func (x *UnwrapRequest) ProtoReflect() protoreflect.Message {
	mi := &file_console_service_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnwrapRequest.ProtoReflect.Descriptor instead.
func (*UnwrapRequest) Descriptor() ([]byte, []int) {
	return file_console_service_proto_rawDescGZIP(), []int{21}
}

func (x *UnwrapRequest) GetHandle() string {
	if x != nil {
		return x.Handle
	}
	return ""
}

type UnwrapResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The released access token (evt_...). This is the only moment it ever
	// leaves the console; the client must store it and never display it.
	Token         string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	MemberId      string `protobuf:"bytes,2,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"` // activated member's immutable id
	Error         string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`                       // Non-empty on error
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnwrapResponse) Reset() {
	*x = UnwrapResponse{}
	mi := &file_console_service_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnwrapResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnwrapResponse) ProtoMessage() {}

func (x *UnwrapResponse) ProtoReflect() protoreflect.Message {
	mi := &file_console_service_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnwrapResponse.ProtoReflect.Descriptor instead.
func (*UnwrapResponse) Descriptor() ([]byte, []int) {
	return file_console_service_proto_rawDescGZIP(), []int{22}
}

func (x *UnwrapResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *UnwrapResponse) GetMemberId() string {
	if x != nil {
		return x.MemberId
	}
	return ""
}

func (x *UnwrapResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_console_service_proto protoreflect.FileDescriptor

const file_console_service_proto_rawDesc = "" +
	"\n" +
	"\x15console_service.proto\x12\x0frune.console.v1\x1a\x1bbuf/validate/validate.proto\":\n" +
	"\x17GetAgentManifestRequest\x12\x1f\n" +
	"\x05token\x18\x01 \x01(\tB\t\xbaH\x06r\x04\x10$\x18$R\x05token\"U\n" +
	"\x18GetAgentManifestResponse\x12#\n" +
	"\rmanifest_json\x18\x01 \x01(\tR\fmanifestJson\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x12\n" +
	"\x10GetCACertRequest\"X\n" +
	"\x11GetCACertResponse\x12\x15\n" +
	"\x06ca_pem\x18\x01 \x01(\fR\x05caPem\x12\x16\n" +
	"\x06sha256\x18\x02 \x01(\tR\x06sha256\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\x85\x02\n" +
	"\rInsertRequest\x12\x1f\n" +
	"\x05token\x18\x01 \x01(\tB\t\xbaH\x06r\x04\x10$\x18$R\x05token\x12\x17\n" +
	"\x02id\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x02id\x12\"\n" +
	"\brmp_item\x18\x03 \x01(\fB\a\xbaH\x04z\x02\x10\x01R\armpItem\x12 \n" +
	"\amm_item\x18\x04 \x01(\fB\a\xbaH\x04z\x02\x10\x01R\x06mmItem\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x05 \x01(\rR\tclusterId\x129\n" +
	"\x14centroid_set_version\x18\x06 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x12centroidSetVersion\x12\x1a\n" +
	"\bmetadata\x18\a \x01(\tR\bmetadata\"6\n" +
	"\x0eInsertResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"6\n" +
	"\x13GetCentroidsRequest\x12\x1f\n" +
	"\x05token\x18\x01 \x01(\tB\t\xbaH\x06r\x04\x10$\x18$R\x05token\"\x90\x01\n" +
	"\rCentroidChunk\x12<\n" +
	"\x06header\x18\x01 \x01(\v2\".rune.console.v1.CentroidSetHeaderH\x00R\x06header\x126\n" +
	"\x05batch\x18\x02 \x01(\v2\x1e.rune.console.v1.CentroidBatchH\x00R\x05batchB\t\n" +
	"\apayload\"m\n" +
	"\x11CentroidSetHeader\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x10\n" +
	"\x03dim\x18\x02 \x01(\x05R\x03dim\x12\x16\n" +
	"\x06preset\x18\x03 \x01(\tR\x06preset\x12\x14\n" +
	"\x05nlist\x18\x04 \x01(\x05R\x05nlist\"H\n" +
	"\rCentroidBatch\x127\n" +
	"\tcentroids\x18\x01 \x03(\v2\x19.rune.console.v1.CentroidR\tcentroids\",\n" +
	"\bCentroid\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x10\n" +
	"\x03vec\x18\x02 \x03(\x02R\x03vec\"s\n" +
	"\rSearchRequest\x12\x1f\n" +
	"\x05token\x18\x01 \x01(\tB\t\xbaH\x06r\x04\x10$\x18$R\x05token\x12 \n" +
	"\x06vector\x18\x02 \x03(\x02B\b\xbaH\x05\x92\x01\x02\b\x01R\x06vector\x12\x1f\n" +
	"\x05top_k\x18\x03 \x01(\x05B\n" +
	"\xbaH\a\x1a\x05\x18\xac\x02(\x01R\x04topK\"M\n" +
	"\tSearchHit\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x01R\x05score\x12\x1a\n" +
	"\bmetadata\x18\x03 \x01(\tR\bmetadata\"V\n" +
	"\x0eSearchResponse\x12.\n" +
	"\x04hits\x18\x01 \x03(\v2\x1a.rune.console.v1.SearchHitR\x04hits\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x89\x01\n" +
	"\x15GetPermissionsRequest\x12\x1f\n" +
	"\x05token\x18\x01 \x01(\tB\t\xbaH\x06r\x04\x10$\x18$R\x05token\x12\x1d\n" +
	"\n" +
	"root_group\x18\x02 \x01(\tR\trootGroup\x120\n" +
	"\x14include_member_roles\x18\x03 \x01(\bR\x12includeMemberRoles\"_\n" +
	"\x0fMembershipEntry\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12\x1d\n" +
	"\n" +
	"group_name\x18\x02 \x01(\tR\tgroupName\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\"\x93\x01\n" +
	"\bTreeNode\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1b\n" +
	"\tparent_id\x18\x03 \x01(\tR\bparentId\x12\x14\n" +
	"\x05depth\x18\x04 \x01(\x05R\x05depth\x12%\n" +
	"\x0eeffective_role\x18\x05 \x01(\tR\reffectiveRole\"n\n" +
	"\n" +
	"MemberRole\x12\x12\n" +
	"\x04user\x18\x01 \x01(\tR\x04user\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\tR\agroupId\x12\x1d\n" +
	"\n" +
	"group_name\x18\x03 \x01(\tR\tgroupName\x12\x12\n" +
	"\x04role\x18\x04 \x01(\tR\x04role\"\xf1\x01\n" +
	"\x16GetPermissionsResponse\x12\x0e\n" +
	"\x02me\x18\x01 \x01(\tR\x02me\x12B\n" +
	"\vmemberships\x18\x02 \x03(\v2 .rune.console.v1.MembershipEntryR\vmemberships\x12-\n" +
	"\x04tree\x18\x03 \x03(\v2\x19.rune.console.v1.TreeNodeR\x04tree\x12>\n" +
	"\fmember_roles\x18\x04 \x03(\v2\x1b.rune.console.v1.MemberRoleR\vmemberRoles\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\"6\n" +
	"\x11LookupWrapRequest\x12!\n" +
	"\x06handle\x18\x01 \x01(\tB\t\xbaH\x06r\x04\x10 \x18 R\x06handle\"\x98\x01\n" +
	"\x12LookupWrapResponse\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\tR\texpiresAt\x12#\n" +
	"\rcreation_path\x18\x04 \x01(\tR\fcreationPath\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\"2\n" +
	"\rUnwrapRequest\x12!\n" +
	"\x06handle\x18\x01 \x01(\tB\t\xbaH\x06r\x04\x10 \x18 R\x06handle\"Y\n" +
	"\x0eUnwrapResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1b\n" +
	"\tmember_id\x18\x02 \x01(\tR\bmemberId\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error2\xc0\x05\n" +
	"\x0eConsoleService\x12g\n" +
	"\x10GetAgentManifest\x12(.rune.console.v1.GetAgentManifestRequest\x1a).rune.console.v1.GetAgentManifestResponse\x12R\n" +
	"\tGetCACert\x12!.rune.console.v1.GetCACertRequest\x1a\".rune.console.v1.GetCACertResponse\x12I\n" +
	"\x06Insert\x12\x1e.rune.console.v1.InsertRequest\x1a\x1f.rune.console.v1.InsertResponse\x12V\n" +
	"\fGetCentroids\x12$.rune.console.v1.GetCentroidsRequest\x1a\x1e.rune.console.v1.CentroidChunk0\x01\x12I\n" +
	"\x06Search\x12\x1e.rune.console.v1.SearchRequest\x1a\x1f.rune.console.v1.SearchResponse\x12a\n" +
	"\x0eGetPermissions\x12&.rune.console.v1.GetPermissionsRequest\x1a'.rune.console.v1.GetPermissionsResponse\x12U\n" +
	"\n" +
	"LookupWrap\x12\".rune.console.v1.LookupWrapRequest\x1a#.rune.console.v1.LookupWrapResponse\x12I\n" +
	"\x06Unwrap\x12\x1e.rune.console.v1.UnwrapRequest\x1a\x1f.rune.console.v1.UnwrapResponseb\x06proto3"

var (
	file_console_service_proto_rawDescOnce sync.Once
	file_console_service_proto_rawDescData []byte
)

func file_console_service_proto_rawDescGZIP() []byte {
	file_console_service_proto_rawDescOnce.Do(func() {
		file_console_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_console_service_proto_rawDesc), len(file_console_service_proto_rawDesc)))
	})
	return file_console_service_proto_rawDescData
}

var file_console_service_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_console_service_proto_goTypes = []any{
	(*GetAgentManifestRequest)(nil),  // 0: rune.console.v1.GetAgentManifestRequest
	(*GetAgentManifestResponse)(nil), // 1: rune.console.v1.GetAgentManifestResponse
	(*GetCACertRequest)(nil),         // 2: rune.console.v1.GetCACertRequest
	(*GetCACertResponse)(nil),        // 3: rune.console.v1.GetCACertResponse
	(*InsertRequest)(nil),            // 4: rune.console.v1.InsertRequest
	(*InsertResponse)(nil),           // 5: rune.console.v1.InsertResponse
	(*GetCentroidsRequest)(nil),      // 6: rune.console.v1.GetCentroidsRequest
	(*CentroidChunk)(nil),            // 7: rune.console.v1.CentroidChunk
	(*CentroidSetHeader)(nil),        // 8: rune.console.v1.CentroidSetHeader
	(*CentroidBatch)(nil),            // 9: rune.console.v1.CentroidBatch
	(*Centroid)(nil),                 // 10: rune.console.v1.Centroid
	(*SearchRequest)(nil),            // 11: rune.console.v1.SearchRequest
	(*SearchHit)(nil),                // 12: rune.console.v1.SearchHit
	(*SearchResponse)(nil),           // 13: rune.console.v1.SearchResponse
	(*GetPermissionsRequest)(nil),    // 14: rune.console.v1.GetPermissionsRequest
	(*MembershipEntry)(nil),          // 15: rune.console.v1.MembershipEntry
	(*TreeNode)(nil),                 // 16: rune.console.v1.TreeNode
	(*MemberRole)(nil),               // 17: rune.console.v1.MemberRole
	(*GetPermissionsResponse)(nil),   // 18: rune.console.v1.GetPermissionsResponse
	(*LookupWrapRequest)(nil),        // 19: rune.console.v1.LookupWrapRequest
	(*LookupWrapResponse)(nil),       // 20: rune.console.v1.LookupWrapResponse
	(*UnwrapRequest)(nil),            // 21: rune.console.v1.UnwrapRequest
	(*UnwrapResponse)(nil),           // 22: rune.console.v1.UnwrapResponse
}
var file_console_service_proto_depIdxs = []int32{
	8,  // 0: rune.console.v1.CentroidChunk.header:type_name -> rune.console.v1.CentroidSetHeader
	9,  // 1: rune.console.v1.CentroidChunk.batch:type_name -> rune.console.v1.CentroidBatch
	10, // 2: rune.console.v1.CentroidBatch.centroids:type_name -> rune.console.v1.Centroid
	12, // 3: rune.console.v1.SearchResponse.hits:type_name -> rune.console.v1.SearchHit
	15, // 4: rune.console.v1.GetPermissionsResponse.memberships:type_name -> rune.console.v1.MembershipEntry
	16, // 5: rune.console.v1.GetPermissionsResponse.tree:type_name -> rune.console.v1.TreeNode
	17, // 6: rune.console.v1.GetPermissionsResponse.member_roles:type_name -> rune.console.v1.MemberRole
	0,  // 7: rune.console.v1.ConsoleService.GetAgentManifest:input_type -> rune.console.v1.GetAgentManifestRequest
	2,  // 8: rune.console.v1.ConsoleService.GetCACert:input_type -> rune.console.v1.GetCACertRequest
	4,  // 9: rune.console.v1.ConsoleService.Insert:input_type -> rune.console.v1.InsertRequest
	6,  // 10: rune.console.v1.ConsoleService.GetCentroids:input_type -> rune.console.v1.GetCentroidsRequest
	11, // 11: rune.console.v1.ConsoleService.Search:input_type -> rune.console.v1.SearchRequest
	14, // 12: rune.console.v1.ConsoleService.GetPermissions:input_type -> rune.console.v1.GetPermissionsRequest
	19, // 13: rune.console.v1.ConsoleService.LookupWrap:input_type -> rune.console.v1.LookupWrapRequest
	21, // 14: rune.console.v1.ConsoleService.Unwrap:input_type -> rune.console.v1.UnwrapRequest
	1,  // 15: rune.console.v1.ConsoleService.GetAgentManifest:output_type -> rune.console.v1.GetAgentManifestResponse
	3,  // 16: rune.console.v1.ConsoleService.GetCACert:output_type -> rune.console.v1.GetCACertResponse
	5,  // 17: rune.console.v1.ConsoleService.Insert:output_type -> rune.console.v1.InsertResponse
	7,  // 18: rune.console.v1.ConsoleService.GetCentroids:output_type -> rune.console.v1.CentroidChunk
	13, // 19: rune.console.v1.ConsoleService.Search:output_type -> rune.console.v1.SearchResponse
	18, // 20: rune.console.v1.ConsoleService.GetPermissions:output_type -> rune.console.v1.GetPermissionsResponse
	20, // 21: rune.console.v1.ConsoleService.LookupWrap:output_type -> rune.console.v1.LookupWrapResponse
	22, // 22: rune.console.v1.ConsoleService.Unwrap:output_type -> rune.console.v1.UnwrapResponse
	15, // [15:23] is the sub-list for method output_type
	7,  // [7:15] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_console_service_proto_init() }
func file_console_service_proto_init() {
	if File_console_service_proto != nil {
		return
	}
	file_console_service_proto_msgTypes[7].OneofWrappers = []any{
		(*CentroidChunk_Header)(nil),
		(*CentroidChunk_Batch)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_console_service_proto_rawDesc), len(file_console_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_console_service_proto_goTypes,
		DependencyIndexes: file_console_service_proto_depIdxs,
		MessageInfos:      file_console_service_proto_msgTypes,
	}.Build()
	File_console_service_proto = out.File
	file_console_service_proto_goTypes = nil
	file_console_service_proto_depIdxs = nil
}
