// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: console_service.proto

package consolepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ConsoleService_GetAgentManifest_FullMethodName = "/rune.console.v1.ConsoleService/GetAgentManifest"
	ConsoleService_GetCACert_FullMethodName        = "/rune.console.v1.ConsoleService/GetCACert"
	ConsoleService_Insert_FullMethodName           = "/rune.console.v1.ConsoleService/Insert"
	ConsoleService_GetCentroids_FullMethodName     = "/rune.console.v1.ConsoleService/GetCentroids"
	ConsoleService_Search_FullMethodName           = "/rune.console.v1.ConsoleService/Search"
	ConsoleService_GetPermissions_FullMethodName   = "/rune.console.v1.ConsoleService/GetPermissions"
	ConsoleService_LookupWrap_FullMethodName       = "/rune.console.v1.ConsoleService/LookupWrap"
	ConsoleService_Unwrap_FullMethodName           = "/rune.console.v1.ConsoleService/Unwrap"
)

// ConsoleServiceClient is the client API for ConsoleService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Rune-Console gRPC service.
// The console holds the FHE SecKey and is the SOLE runespace client; it proxies
// pre-encrypted writes and blind searches to runespace. rune-mcp holds the
// PUBLIC EncKey + the agent_dek, so it encrypts the vector (RMP+MM) and seals
// the metadata locally, then hands the console ciphertext to forward verbatim.
type ConsoleServiceClient interface {
	// Returns the agent manifest: config + the PUBLIC EncKey pair + agent_dek +
	// the current centroid-set version, so rune-mcp can encrypt/seal and route
	// IVF locally. SecKey never leaves the console.
	GetAgentManifest(ctx context.Context, in *GetAgentManifestRequest, opts ...grpc.CallOption) (*GetAgentManifestResponse, error)
	// GetCACert returns the console's CA certificate (PEM) for bootstrap stage 1.
	// Pre-auth and servable over the initial no-TLS connection: the client pins
	// it against the SHA-256 carried in its registration string, then reconnects
	// over TLS. No token; leaks nothing (a public certificate).
	GetCACert(ctx context.Context, in *GetCACertRequest, opts ...grpc.CallOption) (*GetCACertResponse, error)
	// Capture write (pre-encrypted): rune-mcp sends the FHE-encrypted RMP+MM
	// blobs, the IVF cluster assignment, and the sealed metadata; the console
	// forwards them verbatim to runespace (SDK InsertPreEncrypted) — it holds no
	// key for this path and performs no encryption.
	Insert(ctx context.Context, in *InsertRequest, opts ...grpc.CallOption) (*InsertResponse, error)
	// Streams the runespace IVF centroid set (header + id-ordered batches) so
	// rune-mcp can assign each vector's cluster locally before encrypting. The
	// cheap version pointer is in GetAgentManifest; fetch this only on mismatch.
	GetCentroids(ctx context.Context, in *GetCentroidsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CentroidChunk], error)
	// Blind vector search over runespace (recall + capture-time novelty check).
	// The plaintext query is sent to runespace (PCMM); the console decrypts the
	// score blobs (SecKey), ranks, resolves and opens metadata (agent_dek), and
	// returns ranked plaintext hits.
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
	// Returns the caller's own memberships and the depth-annotated group tree
	// they can reach by effective role (recall scope) — requirements 4 and 12.
	// include_member_roles adds the per-user (group, role) listing and is
	// restricted to the organization admin (plan §5, §6-D8, D11).
	GetPermissions(ctx context.Context, in *GetPermissionsRequest, opts ...grpc.CallOption) (*GetPermissionsResponse, error)
	// Pre-validates an invite code and returns who/what it is for, so the
	// client can show the invite before consuming it. Read-only: never consumes
	// the code, never returns the token.
	LookupWrap(ctx context.Context, in *LookupWrapRequest, opts ...grpc.CallOption) (*LookupWrapResponse, error)
	// Exchanges a pending invite code for its sealed access token, exactly
	// once. The consumed state is written to disk before the token is released
	// (a crash can lose an invite, never double-release a token), and the
	// member is advanced invited→active in the same call.
	Unwrap(ctx context.Context, in *UnwrapRequest, opts ...grpc.CallOption) (*UnwrapResponse, error)
}

type consoleServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewConsoleServiceClient(cc grpc.ClientConnInterface) ConsoleServiceClient {
	return &consoleServiceClient{cc}
}

func (c *consoleServiceClient) GetAgentManifest(ctx context.Context, in *GetAgentManifestRequest, opts ...grpc.CallOption) (*GetAgentManifestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAgentManifestResponse)
	err := c.cc.Invoke(ctx, ConsoleService_GetAgentManifest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *consoleServiceClient) GetCACert(ctx context.Context, in *GetCACertRequest, opts ...grpc.CallOption) (*GetCACertResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCACertResponse)
	err := c.cc.Invoke(ctx, ConsoleService_GetCACert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *consoleServiceClient) Insert(ctx context.Context, in *InsertRequest, opts ...grpc.CallOption) (*InsertResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InsertResponse)
	err := c.cc.Invoke(ctx, ConsoleService_Insert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *consoleServiceClient) GetCentroids(ctx context.Context, in *GetCentroidsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CentroidChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ConsoleService_ServiceDesc.Streams[0], ConsoleService_GetCentroids_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetCentroidsRequest, CentroidChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ConsoleService_GetCentroidsClient = grpc.ServerStreamingClient[CentroidChunk]

func (c *consoleServiceClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, ConsoleService_Search_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *consoleServiceClient) GetPermissions(ctx context.Context, in *GetPermissionsRequest, opts ...grpc.CallOption) (*GetPermissionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPermissionsResponse)
	err := c.cc.Invoke(ctx, ConsoleService_GetPermissions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *consoleServiceClient) LookupWrap(ctx context.Context, in *LookupWrapRequest, opts ...grpc.CallOption) (*LookupWrapResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LookupWrapResponse)
	err := c.cc.Invoke(ctx, ConsoleService_LookupWrap_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *consoleServiceClient) Unwrap(ctx context.Context, in *UnwrapRequest, opts ...grpc.CallOption) (*UnwrapResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnwrapResponse)
	err := c.cc.Invoke(ctx, ConsoleService_Unwrap_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConsoleServiceServer is the server API for ConsoleService service.
// All implementations must embed UnimplementedConsoleServiceServer
// for forward compatibility.
//
// Rune-Console gRPC service.
// The console holds the FHE SecKey and is the SOLE runespace client; it proxies
// pre-encrypted writes and blind searches to runespace. rune-mcp holds the
// PUBLIC EncKey + the agent_dek, so it encrypts the vector (RMP+MM) and seals
// the metadata locally, then hands the console ciphertext to forward verbatim.
type ConsoleServiceServer interface {
	// Returns the agent manifest: config + the PUBLIC EncKey pair + agent_dek +
	// the current centroid-set version, so rune-mcp can encrypt/seal and route
	// IVF locally. SecKey never leaves the console.
	GetAgentManifest(context.Context, *GetAgentManifestRequest) (*GetAgentManifestResponse, error)
	// GetCACert returns the console's CA certificate (PEM) for bootstrap stage 1.
	// Pre-auth and servable over the initial no-TLS connection: the client pins
	// it against the SHA-256 carried in its registration string, then reconnects
	// over TLS. No token; leaks nothing (a public certificate).
	GetCACert(context.Context, *GetCACertRequest) (*GetCACertResponse, error)
	// Capture write (pre-encrypted): rune-mcp sends the FHE-encrypted RMP+MM
	// blobs, the IVF cluster assignment, and the sealed metadata; the console
	// forwards them verbatim to runespace (SDK InsertPreEncrypted) — it holds no
	// key for this path and performs no encryption.
	Insert(context.Context, *InsertRequest) (*InsertResponse, error)
	// Streams the runespace IVF centroid set (header + id-ordered batches) so
	// rune-mcp can assign each vector's cluster locally before encrypting. The
	// cheap version pointer is in GetAgentManifest; fetch this only on mismatch.
	GetCentroids(*GetCentroidsRequest, grpc.ServerStreamingServer[CentroidChunk]) error
	// Blind vector search over runespace (recall + capture-time novelty check).
	// The plaintext query is sent to runespace (PCMM); the console decrypts the
	// score blobs (SecKey), ranks, resolves and opens metadata (agent_dek), and
	// returns ranked plaintext hits.
	Search(context.Context, *SearchRequest) (*SearchResponse, error)
	// Returns the caller's own memberships and the depth-annotated group tree
	// they can reach by effective role (recall scope) — requirements 4 and 12.
	// include_member_roles adds the per-user (group, role) listing and is
	// restricted to the organization admin (plan §5, §6-D8, D11).
	GetPermissions(context.Context, *GetPermissionsRequest) (*GetPermissionsResponse, error)
	// Pre-validates an invite code and returns who/what it is for, so the
	// client can show the invite before consuming it. Read-only: never consumes
	// the code, never returns the token.
	LookupWrap(context.Context, *LookupWrapRequest) (*LookupWrapResponse, error)
	// Exchanges a pending invite code for its sealed access token, exactly
	// once. The consumed state is written to disk before the token is released
	// (a crash can lose an invite, never double-release a token), and the
	// member is advanced invited→active in the same call.
	Unwrap(context.Context, *UnwrapRequest) (*UnwrapResponse, error)
	mustEmbedUnimplementedConsoleServiceServer()
}

// UnimplementedConsoleServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedConsoleServiceServer struct{}

func (UnimplementedConsoleServiceServer) GetAgentManifest(context.Context, *GetAgentManifestRequest) (*GetAgentManifestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAgentManifest not implemented")
}
func (UnimplementedConsoleServiceServer) GetCACert(context.Context, *GetCACertRequest) (*GetCACertResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCACert not implemented")
}
func (UnimplementedConsoleServiceServer) Insert(context.Context, *InsertRequest) (*InsertResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Insert not implemented")
}
func (UnimplementedConsoleServiceServer) GetCentroids(*GetCentroidsRequest, grpc.ServerStreamingServer[CentroidChunk]) error {
	return status.Error(codes.Unimplemented, "method GetCentroids not implemented")
}
func (UnimplementedConsoleServiceServer) Search(context.Context, *SearchRequest) (*SearchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Search not implemented")
}
func (UnimplementedConsoleServiceServer) GetPermissions(context.Context, *GetPermissionsRequest) (*GetPermissionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPermissions not implemented")
}
func (UnimplementedConsoleServiceServer) LookupWrap(context.Context, *LookupWrapRequest) (*LookupWrapResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LookupWrap not implemented")
}
func (UnimplementedConsoleServiceServer) Unwrap(context.Context, *UnwrapRequest) (*UnwrapResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Unwrap not implemented")
}
func (UnimplementedConsoleServiceServer) mustEmbedUnimplementedConsoleServiceServer() {}
func (UnimplementedConsoleServiceServer) testEmbeddedByValue()                        {}

// UnsafeConsoleServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConsoleServiceServer will
// result in compilation errors.
type UnsafeConsoleServiceServer interface {
	mustEmbedUnimplementedConsoleServiceServer()
}

func RegisterConsoleServiceServer(s grpc.ServiceRegistrar, srv ConsoleServiceServer) {
	// If the following call panics, it indicates UnimplementedConsoleServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ConsoleService_ServiceDesc, srv)
}

func _ConsoleService_GetAgentManifest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAgentManifestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsoleServiceServer).GetAgentManifest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConsoleService_GetAgentManifest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsoleServiceServer).GetAgentManifest(ctx, req.(*GetAgentManifestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConsoleService_GetCACert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCACertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsoleServiceServer).GetCACert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConsoleService_GetCACert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsoleServiceServer).GetCACert(ctx, req.(*GetCACertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConsoleService_Insert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InsertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsoleServiceServer).Insert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConsoleService_Insert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsoleServiceServer).Insert(ctx, req.(*InsertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConsoleService_GetCentroids_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetCentroidsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ConsoleServiceServer).GetCentroids(m, &grpc.GenericServerStream[GetCentroidsRequest, CentroidChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ConsoleService_GetCentroidsServer = grpc.ServerStreamingServer[CentroidChunk]

func _ConsoleService_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsoleServiceServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConsoleService_Search_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsoleServiceServer).Search(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConsoleService_GetPermissions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPermissionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsoleServiceServer).GetPermissions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConsoleService_GetPermissions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsoleServiceServer).GetPermissions(ctx, req.(*GetPermissionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConsoleService_LookupWrap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LookupWrapRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsoleServiceServer).LookupWrap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConsoleService_LookupWrap_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsoleServiceServer).LookupWrap(ctx, req.(*LookupWrapRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConsoleService_Unwrap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnwrapRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsoleServiceServer).Unwrap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConsoleService_Unwrap_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsoleServiceServer).Unwrap(ctx, req.(*UnwrapRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ConsoleService_ServiceDesc is the grpc.ServiceDesc for ConsoleService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ConsoleService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rune.console.v1.ConsoleService",
	HandlerType: (*ConsoleServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAgentManifest",
			Handler:    _ConsoleService_GetAgentManifest_Handler,
		},
		{
			MethodName: "GetCACert",
			Handler:    _ConsoleService_GetCACert_Handler,
		},
		{
			MethodName: "Insert",
			Handler:    _ConsoleService_Insert_Handler,
		},
		{
			MethodName: "Search",
			Handler:    _ConsoleService_Search_Handler,
		},
		{
			MethodName: "GetPermissions",
			Handler:    _ConsoleService_GetPermissions_Handler,
		},
		{
			MethodName: "LookupWrap",
			Handler:    _ConsoleService_LookupWrap_Handler,
		},
		{
			MethodName: "Unwrap",
			Handler:    _ConsoleService_Unwrap_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetCentroids",
			Handler:       _ConsoleService_GetCentroids_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "console_service.proto",
}
